/**
 * Database operations are optimized for ClickHouse migration.
 * Test results are stored in append mode only.
 * For future: Redis in hot path, ClickHouse in control plane.
 */
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';
import { uuidv7 } from 'uuidv7';

import { IAssertResult } from './schemas';


/**
 * Prisma client instance for database operations.
 */
const connectionString = `${process.env.DATABASE_URL}`;
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter});

/**
 * Save the test result and all assert results to the database.
 * @param {string} run_id - The run ID.
 * @param {string} test_id - The test ID.
 * @param {string} prompt - The prompt used in the test.
 * @param {string} output - The output generated by the model.
 * @param {boolean} is_passed - Whether the test passed.
 * @param {IAssertResult[]} results - Array of assert results.
 */
export async function saveTestResult(
  run_id: string,
  test_id: string,
  prompt: string,
  output: string,
  is_passed: boolean,
  results: IAssertResult[]
) {
  // NOTE: Save test details for each assert. This allows to have detailed insights and metrics on asserts performance.
  await Promise.allSettled(results.map((result: IAssertResult) =>
    prisma.assertResult.create({
      data: {
        id: uuidv7(),
        test_id,
        run_id, // NOTE: For future, in ClickHouse this will allow to make filtration without Join.
        name: result.name,
        passed: result.passed,
        score: result.score,
        reason: result.reason,
      }
    })
  ));
  // NOTE: Save test header for tracking and filtration.
  await prisma.testResult.create({
    data: {
      id: test_id,
      run_id,
      prompt,
      output,
      passed: is_passed,
    }
  });
}
